# File: .github/workflows/main.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Weekly retraining

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Retrain model
      run: |
        python train.py # Your training script

    - name: Save model artifact
      uses: actions/upload-artifact@v2
      with:
        name: best_model
        path: best_model.pkl

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download model artifact
      uses: actions/download-artifact@v2
      with:
        name: best_model

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t fraud_detection_api .
        docker tag fraud_detection_api:latest ${{ secrets.DOCKER_USERNAME }}/fraud_detection_api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/fraud_detection_api:latest
